# Site Settings
title: My Resume
url: 'http://aronneagu.github.io'
baseurl: '' 
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Aron Neagu
tagline: Devops engineer
pic: profile.jpeg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "I currently working as systems engineer for Wowcher. My tasks are related to automating the provisioning
and configuration management of the cloud resources. I am also involved in improving the software delivery pipeline,
and this means bringing consisteny in the way we build and deploy the applications, as well as implementing the
practices of CI/CD. In my previous role at Optimy, I was the only system administrator for a startup in Belgium. 
My role was again maintaining and improving the AWS infrastructure. I am thourough, have an eye for details, 
I am a hard worked, eager to learn about new technologies, as well as an excellent team player. I am passionate about
Linux as the LPIC-1 certification will show."

#sidebar links
email: aron.neagu@gmail.com
phone: 0743 4646 067
#website: blog.webjeda.com #do not add http://
linkedin: aronneagu
github: aronneagu
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-118623578-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
