# Site Settings
title: My Resume
url: 'http://aronneagu.github.io'
baseurl: '' 
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Aron Neagu
tagline: Devops engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "Don't forget to add a summary of yourself"

#sidebar links
email: aron.neagu@gmail.com
phone: 0743 4646 067
#website: blog.webjeda.com #do not add http://
linkedin: aronneagu
github: aronneagu
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-118623578-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
